name: Release

# Action will run on every pull-request to master branch
# 05.10.2020: release app can't be signed now, so it builds debug version. It will be fixed at the next sprint
on:
  pull_request:
    branches:
      - master

jobs:
  Build:
    name: Build app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          
      - name: Assemble debug version
        run: bash ./gradlew AssembleDebug