name: Release

# Action will run on every pull-request to master branch
on:
  pull_request:
    branches:
      - master

jobs:
  Build:
    name: Build app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      
      - name: Take version code
        run: echo VERSION_CODE=${{ github.run_number }} > ./version.properties

      - name: Build with Gradle
        run: bash ./gradlew assembleRelease
        env:
          RELEASE_STORE_PASSWORD: ${{ secrets.RELEASE_STORE_PASSWORD }}
          RELEASE_KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}
          RELEASE_KEY_ALIAS: ${{ secrets.RELEASE_KEY_ALIAS }}

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app-release
          path: app/build/outputs/apk/release/app-release.apk