name: Tests

# Action will run on every push to the development branch and pull-request to master/dev
# There are two parallel jobs to increase the efficiency
# 05.10.2020: there are no UI tests yet, so the second job is commented
on:
  push:
    branches: 
    - Development
  pull-request:
    branches: 
    - Development
    - master

jobs:
  Unit:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          
      - name: Run unit tests
        run: bash ./gradlew test 

#  UI:
#    name: UI tests
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v1
#      
#      - name: set up JDK 1.8
#        uses: actions/setup-java@v1
#        with:
#          java-version: 1.8
#          
#      - name: Make gradlew executable
#        run: chmod +x ./gradlew
#        
#      - name: Build with Gradle
#        run: ./gradlew assembleDebug
